version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: mariogmz
      POSTGRES_PASSWORD: mariogmz123
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: mariogmz
      DB_PASSWORD: mariogmz123
      PORT: 3000
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p $${PORT} -b '0.0.0.0'"
    volumes:
      - .:/var/www/current
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/var/www/current
    ports:
      - "80:80"
    depends_on:
      - app
  client:
    image: "node:10-alpine"
    user: "node"
    working_dir: /var/www/current/react-app
    volumes:
      - ./react-app:/var/www/current/react-app
    ports:
      - "3001:3001"
    command: "yarn start"
    depends_on:
      - db
