version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: mariogmz
      POSTGRES_PASSWORD: mariogmz123
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web_api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: mariogmz
      DB_PASSWORD: mariogmz123
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/mariogmz
    ports:
      - "3001:3001"
    depends_on:
      - db
