version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME-app:$IMAGE_TAG . -f docker/app/production.Dockerfile
      - docker build -t $IMAGE_REPO_NAME-web:$IMAGE_TAG . -f docker/web/Dockerfile
      - docker tag $IMAGE_REPO_NAME-app:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME-app:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME-web:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME-web:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME-app:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME-web:$IMAGE_TAG
artifacts:
  files:
    - 'aws/imagedefinitions.json'
  name: $(IMAGE_REPO_NAME)-$(AWS_DEFAULT_REGION)-$(date +%Y-%m-%d)
