version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building production bundle for client
      - cd react-app
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'react-app/build/**/*'
  name: $(APP_NAME)-$(AWS_DEFAULT_REGION)-client-$(date +%Y-%m-%d)
