# PostgreSQL. Versions 9.1 and up are supported.
postgres: &postgres
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5

development:
  <<: *postgres
  database: mariogmz_development

test:
  <<: *postgres
  database: mariogmz_test

production:
  <<: *postgres
  url: <%= ENV['DB_URL'] %>
  pool: 10
